### ISSUE TITLE
Update Scripts to Wine 3.0

### ISSUE THREAD

**Issue by LukeShortCloud** [ekultails/playonlinux_user_repo#6]
Most of the scripts are using the stable Wine branch and, more specifically, 2.0. Wine 3.0 has come out a few months ago and should be tested out for each existing script.

**Comment by GuestSneezeOSDev** [comment]
You Should Updated To 9.0

**Comment by LukeShortCloud** [comment]
PlayOnLinux is no longer under active development. I moved all of my scripts over to Lutris a long time ago. I will archive this repository.
